//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Services.AuthenticationServiceClient
{

#pragma warning disable 1591,618
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wcfservices.riversand.com", ConfigurationName="AuthenticationServiceClient.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IAuthenticationService/AuthenticateUser", ReplyAction="http://wcfservices.riversand.com/IAuthenticationService/AuthenticateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IAuthenticationService/AuthenticateUserMDMExcept" +
            "ionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        bool AuthenticateUser(string userLoginName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IAuthenticationService/GetSecurityPrincipal", ReplyAction="http://wcfservices.riversand.com/IAuthenticationService/GetSecurityPrincipalRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IAuthenticationService/GetSecurityPrincipalMDMEx" +
            "ceptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterSystem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataSecurity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Permission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserCredentialRequestContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserCredentialRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.OperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, long[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Claims.ClaimsIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        MDM.BusinessObjects.SecurityPrincipal GetSecurityPrincipal(string userLoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IAuthenticationService/ProcessUserCredentialRequ" +
            "est", ReplyAction="http://wcfservices.riversand.com/IAuthenticationService/ProcessUserCredentialRequ" +
            "estResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IAuthenticationService/ProcessUserCredentialRequ" +
            "estMDMExceptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityPrincipal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterSystem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataSecurity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Permission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.PermissionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserCredentialRequestContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserCredentialRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, long[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Security.Claims.ClaimsIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        MDM.BusinessObjects.OperationResult ProcessUserCredentialRequest(MDM.BusinessObjects.UserCredentialRequestContext userRequestContext, MDM.BusinessObjects.CallerContext callerContext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : MDM.Services.AuthenticationServiceClient.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<MDM.Services.AuthenticationServiceClient.IAuthenticationService>, MDM.Services.AuthenticationServiceClient.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AuthenticateUser(string userLoginName, string password) {
            return base.Channel.AuthenticateUser(userLoginName, password);
        }
        
        public MDM.BusinessObjects.SecurityPrincipal GetSecurityPrincipal(string userLoginName) {
            return base.Channel.GetSecurityPrincipal(userLoginName);
        }
        
        public MDM.BusinessObjects.OperationResult ProcessUserCredentialRequest(MDM.BusinessObjects.UserCredentialRequestContext userRequestContext, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.ProcessUserCredentialRequest(userRequestContext, callerContext);
        }
    }
    #pragma warning restore 1591,618
}
