//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.MDM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RS.MDM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///   &lt;xsl:output indent=&quot;no&quot; method=&quot;html&quot;/&gt;
        ///
        ///   &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;HTML&gt;
        ///         &lt;HEAD&gt;
        ///            &lt;SCRIPT&gt;
        ///               &lt;xsl:comment&gt;&lt;![CDATA[
        ///                  function f(e){
        ///                     if (e.className==&quot;ci&quot;) {
        ///                       if (e.children(0).innerText.indexOf(&quot;\n&quot;)&gt;0) fix(e,&quot;cb&quot;);
        ///                     }
        ///                     if (e.className==&quot;di&quot;) {
        ///                       if (e.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStyleSheet {
            get {
                return ResourceManager.GetString("DefaultStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///
        ///Pretty XML Tree Viewer 1.0 (15 Oct 2001):
        ///An XPath/XSLT visualisation tool for XML documents
        ///
        ///Use this stylesheet to produce an HTML document containing an ASCII art
        ///representation of an XML document&apos;s node tree, as exposed by the XML parser
        ///and interpreted by the XSLT processor. Note that the parser may not expose
        ///comments to the XSLT processor.
        ///
        ///Usage notes
        ///===========
        ///
        ///The output from this stylesheet is HTML that relies heavily on the tree-view.css
        ///stylesheet. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xml2HtmlStyleSheet {
            get {
                return ResourceManager.GetString("Xml2HtmlStyleSheet", resourceCulture);
            }
        }
    }
}
