//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Services.WorkflowDesignerServiceClient
{
#pragma warning disable 1591,618
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingProfile", Namespace="http://schemas.datacontract.org/2004/07/System.Activities.Tracking")]
    [System.SerializableAttribute()]
    public partial class TrackingProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityDefinitionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility ImplementationVisibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery> QueriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityDefinitionId {
            get {
                return this.ActivityDefinitionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityDefinitionIdField, value) != true)) {
                    this.ActivityDefinitionIdField = value;
                    this.RaisePropertyChanged("ActivityDefinitionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility ImplementationVisibility {
            get {
                return this.ImplementationVisibilityField;
            }
            set {
                if ((this.ImplementationVisibilityField.Equals(value) != true)) {
                    this.ImplementationVisibilityField = value;
                    this.RaisePropertyChanged("ImplementationVisibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery> Queries {
            get {
                return this.QueriesField;
            }
            set {
                if ((object.ReferenceEquals(this.QueriesField, value) != true)) {
                    this.QueriesField = value;
                    this.RaisePropertyChanged("Queries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImplementationVisibility", Namespace="http://schemas.datacontract.org/2004/07/System.Activities.Tracking")]
    public enum ImplementationVisibility : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RootScope = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingQuery", Namespace="http://schemas.datacontract.org/2004/07/System.Activities.Tracking")]
    [System.SerializableAttribute()]
    public partial class TrackingQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> QueryAnnotationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> QueryAnnotations {
            get {
                return this.QueryAnnotationsField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryAnnotationsField, value) != true)) {
                    this.QueryAnnotationsField = value;
                    this.RaisePropertyChanged("QueryAnnotations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wcfservices.riversand.com", ConfigurationName="WorkflowDesignerServiceClient.IWorkflowDesignerService")]
    public interface IWorkflowDesignerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAppConfigValue", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAppConfigValueRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AssignmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.CommentsRequired))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.TrackedActivityInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObjectCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowMDMObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.Workflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.ActivityAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.ActivityAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingQuery))]
        MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueResponse GetAppConfigValue(MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAppConfigValue", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAppConfigValueRespon" +
            "se")]
        System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueResponse> GetAppConfigValueAsync(MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetWorkflowViewDetails", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetWorkflowViewDetailsR" +
            "esponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AssignmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.CommentsRequired))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.TrackedActivityInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObjectCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowMDMObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.Workflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.ActivityAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.ActivityAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingQuery))]
        MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsResponse GetWorkflowViewDetails(MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetWorkflowViewDetails", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetWorkflowViewDetailsR" +
            "esponse")]
        System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsResponse> GetWorkflowViewDetailsAsync(MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessWorkflows", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessWorkflowsRespons" +
            "e")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AssignmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.CommentsRequired))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.TrackedActivityInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObjectCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowMDMObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.Workflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.ActivityAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.ActivityAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingQuery))]
        MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsResponse ProcessWorkflows(MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessWorkflows", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessWorkflowsRespons" +
            "e")]
        System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsResponse> ProcessWorkflowsAsync(MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessActivities", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessActivitiesRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AssignmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.CommentsRequired))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.TrackedActivityInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObjectCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowMDMObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.Workflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.ActivityAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.ActivityAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingQuery))]
        MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesResponse ProcessActivities(MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessActivities", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/ProcessActivitiesRespon" +
            "se")]
        System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesResponse> ProcessActivitiesAsync(MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAllWorkflowDetails", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAllWorkflowDetailsRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AssignmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.CommentsRequired))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.TrackedActivityInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObjectCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowMDMObject>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowMDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.Workflow))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.WorkflowActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.ActivityAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Workflow.ActivityAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.ImplementationVisibility))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Services.WorkflowDesignerServiceClient.TrackingQuery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Services.WorkflowDesignerServiceClient.TrackingQuery))]
        MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsResponse GetAllWorkflowDetails(MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAllWorkflowDetails", ReplyAction="http://wcfservices.riversand.com/IWorkflowDesignerService/GetAllWorkflowDetailsRe" +
            "sponse")]
        System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsResponse> GetAllWorkflowDetailsAsync(MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppConfigValue", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetAppConfigValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public string keyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public GetAppConfigValueRequest() {
        }
        
        public GetAppConfigValueRequest(string keyName, MDM.BusinessObjects.OperationResult operationResult) {
            this.keyName = keyName;
            this.operationResult = operationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppConfigValueResponse", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetAppConfigValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public string GetAppConfigValueResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public GetAppConfigValueResponse() {
        }
        
        public GetAppConfigValueResponse(string GetAppConfigValueResult, MDM.BusinessObjects.OperationResult operationResult) {
            this.GetAppConfigValueResult = GetAppConfigValueResult;
            this.operationResult = operationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkflowViewDetails", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetWorkflowViewDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public int workflowVersionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public string instanceGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public MDM.BusinessObjects.Workflow.WorkflowVersion workflowVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=3)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo> trackedActivityCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=4)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=5)]
        public MDM.BusinessObjects.CallerContext callerContext;
        
        public GetWorkflowViewDetailsRequest() {
        }
        
        public GetWorkflowViewDetailsRequest(int workflowVersionID, string instanceGuid, MDM.BusinessObjects.Workflow.WorkflowVersion workflowVersion, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo> trackedActivityCollection, MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            this.workflowVersionID = workflowVersionID;
            this.instanceGuid = instanceGuid;
            this.workflowVersion = workflowVersion;
            this.trackedActivityCollection = trackedActivityCollection;
            this.operationResult = operationResult;
            this.callerContext = callerContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkflowViewDetailsResponse", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetWorkflowViewDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public MDM.BusinessObjects.Workflow.WorkflowVersion workflowVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo> trackedActivityCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public GetWorkflowViewDetailsResponse() {
        }
        
        public GetWorkflowViewDetailsResponse(MDM.BusinessObjects.Workflow.WorkflowVersion workflowVersion, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo> trackedActivityCollection, MDM.BusinessObjects.OperationResult operationResult) {
            this.workflowVersion = workflowVersion;
            this.trackedActivityCollection = trackedActivityCollection;
            this.operationResult = operationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessWorkflows", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class ProcessWorkflowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public string loginUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=3)]
        public MDM.BusinessObjects.CallerContext callerContext;
        
        public ProcessWorkflowsRequest() {
        }
        
        public ProcessWorkflowsRequest(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflows, string loginUser, MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            this.workflows = workflows;
            this.loginUser = loginUser;
            this.operationResult = operationResult;
            this.callerContext = callerContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessWorkflowsResponse", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class ProcessWorkflowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public MDM.BusinessObjects.Workflow.WorkflowVersion ProcessWorkflowsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public ProcessWorkflowsResponse() {
        }
        
        public ProcessWorkflowsResponse(MDM.BusinessObjects.Workflow.WorkflowVersion ProcessWorkflowsResult, MDM.BusinessObjects.OperationResult operationResult) {
            this.ProcessWorkflowsResult = ProcessWorkflowsResult;
            this.operationResult = operationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessActivities", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class ProcessActivitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public string loginUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=3)]
        public MDM.BusinessObjects.CallerContext callerContext;
        
        public ProcessActivitiesRequest() {
        }
        
        public ProcessActivitiesRequest(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivities, string loginUser, MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            this.workflowActivities = workflowActivities;
            this.loginUser = loginUser;
            this.operationResult = operationResult;
            this.callerContext = callerContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessActivitiesResponse", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class ProcessActivitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public int ProcessActivitiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public ProcessActivitiesResponse() {
        }
        
        public ProcessActivitiesResponse(int ProcessActivitiesResult, MDM.BusinessObjects.OperationResult operationResult) {
            this.ProcessActivitiesResult = ProcessActivitiesResult;
            this.operationResult = operationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllWorkflowDetails", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetAllWorkflowDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflowCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion> workflowVersionCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivityCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=3)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=4)]
        public MDM.BusinessObjects.CallerContext callerContext;
        
        public GetAllWorkflowDetailsRequest() {
        }
        
        public GetAllWorkflowDetailsRequest(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflowCollection, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion> workflowVersionCollection, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivityCollection, MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            this.workflowCollection = workflowCollection;
            this.workflowVersionCollection = workflowVersionCollection;
            this.workflowActivityCollection = workflowActivityCollection;
            this.operationResult = operationResult;
            this.callerContext = callerContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllWorkflowDetailsResponse", WrapperNamespace="http://wcfservices.riversand.com", IsWrapped=true)]
    public partial class GetAllWorkflowDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=0)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflowCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=1)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion> workflowVersionCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=2)]
        public System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivityCollection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcfservices.riversand.com", Order=3)]
        public MDM.BusinessObjects.OperationResult operationResult;
        
        public GetAllWorkflowDetailsResponse() {
        }
        
        public GetAllWorkflowDetailsResponse(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflowCollection, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion> workflowVersionCollection, System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivityCollection, MDM.BusinessObjects.OperationResult operationResult) {
            this.workflowCollection = workflowCollection;
            this.workflowVersionCollection = workflowVersionCollection;
            this.workflowActivityCollection = workflowActivityCollection;
            this.operationResult = operationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkflowDesignerServiceChannel : MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkflowDesignerServiceClient : System.ServiceModel.ClientBase<MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService>, MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService {
        
        public WorkflowDesignerServiceClient() {
        }
        
        public WorkflowDesignerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkflowDesignerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowDesignerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowDesignerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueResponse MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService.GetAppConfigValue(MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest request) {
            return base.Channel.GetAppConfigValue(request);
        }
        
        public string GetAppConfigValue(string keyName, ref MDM.BusinessObjects.OperationResult operationResult) {
            MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest inValue = new MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest();
            inValue.keyName = keyName;
            inValue.operationResult = operationResult;
            MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueResponse retVal = ((MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService)(this)).GetAppConfigValue(inValue);
            operationResult = retVal.operationResult;
            return retVal.GetAppConfigValueResult;
        }
        
        public System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueResponse> GetAppConfigValueAsync(MDM.Services.WorkflowDesignerServiceClient.GetAppConfigValueRequest request) {
            return base.Channel.GetAppConfigValueAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsResponse MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService.GetWorkflowViewDetails(MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest request) {
            return base.Channel.GetWorkflowViewDetails(request);
        }
        
        public void GetWorkflowViewDetails(int workflowVersionID, string instanceGuid, ref MDM.BusinessObjects.Workflow.WorkflowVersion workflowVersion, ref System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.TrackedActivityInfo> trackedActivityCollection, ref MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest inValue = new MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest();
            inValue.workflowVersionID = workflowVersionID;
            inValue.instanceGuid = instanceGuid;
            inValue.workflowVersion = workflowVersion;
            inValue.trackedActivityCollection = trackedActivityCollection;
            inValue.operationResult = operationResult;
            inValue.callerContext = callerContext;
            MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsResponse retVal = ((MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService)(this)).GetWorkflowViewDetails(inValue);
            workflowVersion = retVal.workflowVersion;
            trackedActivityCollection = retVal.trackedActivityCollection;
            operationResult = retVal.operationResult;
        }
        
        public System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsResponse> GetWorkflowViewDetailsAsync(MDM.Services.WorkflowDesignerServiceClient.GetWorkflowViewDetailsRequest request) {
            return base.Channel.GetWorkflowViewDetailsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsResponse MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService.ProcessWorkflows(MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest request) {
            return base.Channel.ProcessWorkflows(request);
        }
        
        public MDM.BusinessObjects.Workflow.WorkflowVersion ProcessWorkflows(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflows, string loginUser, ref MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest inValue = new MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest();
            inValue.workflows = workflows;
            inValue.loginUser = loginUser;
            inValue.operationResult = operationResult;
            inValue.callerContext = callerContext;
            MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsResponse retVal = ((MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService)(this)).ProcessWorkflows(inValue);
            operationResult = retVal.operationResult;
            return retVal.ProcessWorkflowsResult;
        }
        
        public System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsResponse> ProcessWorkflowsAsync(MDM.Services.WorkflowDesignerServiceClient.ProcessWorkflowsRequest request) {
            return base.Channel.ProcessWorkflowsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesResponse MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService.ProcessActivities(MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest request) {
            return base.Channel.ProcessActivities(request);
        }
        
        public int ProcessActivities(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivities, string loginUser, ref MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest inValue = new MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest();
            inValue.workflowActivities = workflowActivities;
            inValue.loginUser = loginUser;
            inValue.operationResult = operationResult;
            inValue.callerContext = callerContext;
            MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesResponse retVal = ((MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService)(this)).ProcessActivities(inValue);
            operationResult = retVal.operationResult;
            return retVal.ProcessActivitiesResult;
        }
        
        public System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesResponse> ProcessActivitiesAsync(MDM.Services.WorkflowDesignerServiceClient.ProcessActivitiesRequest request) {
            return base.Channel.ProcessActivitiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsResponse MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService.GetAllWorkflowDetails(MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest request) {
            return base.Channel.GetAllWorkflowDetails(request);
        }
        
        public void GetAllWorkflowDetails(ref System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.Workflow> workflowCollection, ref System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowVersion> workflowVersionCollection, ref System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Workflow.WorkflowActivity> workflowActivityCollection, ref MDM.BusinessObjects.OperationResult operationResult, MDM.BusinessObjects.CallerContext callerContext) {
            MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest inValue = new MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest();
            inValue.workflowCollection = workflowCollection;
            inValue.workflowVersionCollection = workflowVersionCollection;
            inValue.workflowActivityCollection = workflowActivityCollection;
            inValue.operationResult = operationResult;
            inValue.callerContext = callerContext;
            MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsResponse retVal = ((MDM.Services.WorkflowDesignerServiceClient.IWorkflowDesignerService)(this)).GetAllWorkflowDetails(inValue);
            workflowCollection = retVal.workflowCollection;
            workflowVersionCollection = retVal.workflowVersionCollection;
            workflowActivityCollection = retVal.workflowActivityCollection;
            operationResult = retVal.operationResult;
        }
        
        public System.Threading.Tasks.Task<MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsResponse> GetAllWorkflowDetailsAsync(MDM.Services.WorkflowDesignerServiceClient.GetAllWorkflowDetailsRequest request) {
            return base.Channel.GetAllWorkflowDetailsAsync(request);
        }
    }
    #pragma warning restore 1591,618
}
