//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.Services.KnowledgeBaseServiceClient {


#pragma warning disable 1591, 618
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wcfservices.riversand.com", ConfigurationName="KnowledgeBaseServiceClient.IKnowledgeBaseService")]
    public interface IKnowledgeBaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocale", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocaleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocaleMDMExceptionDetai" +
            "lsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.Locale GetLocale(int localeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocale", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocaleResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.Locale> GetLocaleAsync(int localeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAvailableLocales", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAvailableLocalesRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAvailableLocalesMDMExce" +
            "ptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.LocaleCollection GetAvailableLocales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAvailableLocales", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAvailableLocalesRespons" +
            "e")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetAvailableLocalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLocales", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLocalesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLocalesMDMExceptionD" +
            "etailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.LocaleCollection GetAllLocales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLocales", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLocalesResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetAllLocalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocalesByContainer", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocalesByContainerRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocalesByContainerMDMEx" +
            "ceptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.LocaleCollection GetLocalesByContainer(int containerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocalesByContainer", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetLocalesByContainerRespo" +
            "nse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetLocalesByContainerAsync(int containerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLookupTableNames", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLookupTableNamesResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLookupTableNamesMDME" +
            "xceptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        System.Collections.ObjectModel.Collection<string> GetAllLookupTableNames(MDM.BusinessObjects.CallerContext callerContext, MDM.BusinessObjects.LookupContext lookupContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLookupTableNames", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllLookupTableNamesResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<string>> GetAllLookupTableNamesAsync(MDM.BusinessObjects.CallerContext callerContext, MDM.BusinessObjects.LookupContext lookupContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllWordLists", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllWordListsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllWordListsMDMExceptio" +
            "nDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.WordListsCollection GetAllWordLists(MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllWordLists", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetAllWordListsResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.WordListsCollection> GetAllWordListsAsync(MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListById", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByIdMDMExceptio" +
            "nDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.WordList GetWordListById(int wordListId, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListById", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByIdResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.WordList> GetWordListByIdAsync(int wordListId, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByName", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByNameMDMExcept" +
            "ionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.WordList GetWordListByName(string wordListName, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByName", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordListByNameResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.WordList> GetWordListByNameAsync(string wordListName, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CreateWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/CreateWordListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CreateWordListMDMException" +
            "DetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Locale))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LocaleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Locale>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LookupContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupTableFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupValueFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordListsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.OperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementReportSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.WordElementColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SearchOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        MDM.BusinessObjects.OperationResult CreateWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CreateWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/CreateWordListResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> CreateWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/UpdateWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/UpdateWordListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/UpdateWordListMDMException" +
            "DetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Locale))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LocaleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Locale>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LookupContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupTableFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupValueFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordListsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.OperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementReportSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.WordElementColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SearchOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        MDM.BusinessObjects.OperationResult UpdateWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/UpdateWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/UpdateWordListResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> UpdateWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/DeleteWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/DeleteWordListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/DeleteWordListMDMException" +
            "DetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DataModel.DataModelOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.EntityOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<long>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, MDM.BusinessObjects.Row>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<long, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, long>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Locale))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LocaleEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.Core.UserAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.UserAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LocaleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Locale>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMPublisher))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.EventSubscriber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.MDMCenterModules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.LookupContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupTableFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.LookupValueFilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordListsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordList>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.WordElement>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ErrorCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InformationCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Information>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Information))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.OperationResultStatusEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WarningCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Warning>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Warning))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Table))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ColumnCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Column>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RowCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Row))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CellCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.Cell>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.Cell))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.AttributeOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.AttributeOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AttributeModelType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.RelationshipOperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.RelationshipOperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ObjectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.AuthenticationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRoleCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityRole>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SecurityUserType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.SecurityUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.SecurityUser>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferences))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.UserPreferencesCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.UserPreferences>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.OperationResultCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.InterfaceContractCollection<object, MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.ItemContractCollection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.OperationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.WordElementReportSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSearchRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.WordElementColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.SearchOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.GenericSortRule<MDM.Core.WordElementColumn>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NamedDataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfoCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.DataQualityIndicatorFailureInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResultsCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.DQM.NormalizationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TraceSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.TracingMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.InterfaceContractCollection<object, MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.Core.ItemContractCollection<MDM.BusinessObjects.DQM.NormalizationResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MDM.BusinessObjects.CallerContext))]
        MDM.BusinessObjects.OperationResult DeleteWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/DeleteWordList", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/DeleteWordListResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> DeleteWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/ProcessWordLists", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/ProcessWordListsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/ProcessWordListsMDMExcepti" +
            "onDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.OperationResultCollection ProcessWordLists(MDM.BusinessObjects.WordListsCollection wordLists, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/ProcessWordLists", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/ProcessWordListsResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResultCollection> ProcessWordListsAsync(MDM.BusinessObjects.WordListsCollection wordLists, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordElements", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordElementsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordElementsMDMExceptio" +
            "nDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.WordElementsCollection GetWordElements(MDM.BusinessObjects.WordElementReportSettings pagingCriteria, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordElements", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/GetWordElementsResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.WordElementsCollection> GetWordElementsAsync(MDM.BusinessObjects.WordElementReportSettings pagingCriteria, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CheckWordlistForDuplicateS" +
            "ubstitute", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/CheckWordlistForDuplicateS" +
            "ubstituteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MDM.BusinessObjects.MDMExceptionDetails), Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CheckWordlistForDuplicateS" +
            "ubstituteMDMExceptionDetailsFault", Name="MDMExceptionDetails", Namespace="http://mdmobjects.riversand.com/")]
        MDM.BusinessObjects.WordElement CheckWordlistForDuplicateSubstitute(int wordlistId, string substitute, bool ignoreCase, MDM.BusinessObjects.CallerContext callerContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcfservices.riversand.com/IKnowledgeBaseService/CheckWordlistForDuplicateS" +
            "ubstitute", ReplyAction="http://wcfservices.riversand.com/IKnowledgeBaseService/CheckWordlistForDuplicateS" +
            "ubstituteResponse")]
        System.Threading.Tasks.Task<MDM.BusinessObjects.WordElement> CheckWordlistForDuplicateSubstituteAsync(int wordlistId, string substitute, bool ignoreCase, MDM.BusinessObjects.CallerContext callerContext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKnowledgeBaseServiceChannel : MDM.Services.KnowledgeBaseServiceClient.IKnowledgeBaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KnowledgeBaseServiceClient : System.ServiceModel.ClientBase<MDM.Services.KnowledgeBaseServiceClient.IKnowledgeBaseService>, MDM.Services.KnowledgeBaseServiceClient.IKnowledgeBaseService {
        
        public KnowledgeBaseServiceClient() {
        }
        
        public KnowledgeBaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KnowledgeBaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnowledgeBaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnowledgeBaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MDM.BusinessObjects.Locale GetLocale(int localeId) {
            return base.Channel.GetLocale(localeId);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.Locale> GetLocaleAsync(int localeId) {
            return base.Channel.GetLocaleAsync(localeId);
        }
        
        public MDM.BusinessObjects.LocaleCollection GetAvailableLocales() {
            return base.Channel.GetAvailableLocales();
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetAvailableLocalesAsync() {
            return base.Channel.GetAvailableLocalesAsync();
        }
        
        public MDM.BusinessObjects.LocaleCollection GetAllLocales() {
            return base.Channel.GetAllLocales();
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetAllLocalesAsync() {
            return base.Channel.GetAllLocalesAsync();
        }
        
        public MDM.BusinessObjects.LocaleCollection GetLocalesByContainer(int containerId) {
            return base.Channel.GetLocalesByContainer(containerId);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.LocaleCollection> GetLocalesByContainerAsync(int containerId) {
            return base.Channel.GetLocalesByContainerAsync(containerId);
        }
        
        public System.Collections.ObjectModel.Collection<string> GetAllLookupTableNames(MDM.BusinessObjects.CallerContext callerContext, MDM.BusinessObjects.LookupContext lookupContext) {
            return base.Channel.GetAllLookupTableNames(callerContext, lookupContext);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<string>> GetAllLookupTableNamesAsync(MDM.BusinessObjects.CallerContext callerContext, MDM.BusinessObjects.LookupContext lookupContext) {
            return base.Channel.GetAllLookupTableNamesAsync(callerContext, lookupContext);
        }
        
        public MDM.BusinessObjects.WordListsCollection GetAllWordLists(MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetAllWordLists(callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.WordListsCollection> GetAllWordListsAsync(MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetAllWordListsAsync(callerContext);
        }
        
        public MDM.BusinessObjects.WordList GetWordListById(int wordListId, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordListById(wordListId, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.WordList> GetWordListByIdAsync(int wordListId, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordListByIdAsync(wordListId, callerContext);
        }
        
        public MDM.BusinessObjects.WordList GetWordListByName(string wordListName, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordListByName(wordListName, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.WordList> GetWordListByNameAsync(string wordListName, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordListByNameAsync(wordListName, callerContext);
        }
        
        public MDM.BusinessObjects.OperationResult CreateWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.CreateWordList(wordList, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> CreateWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.CreateWordListAsync(wordList, callerContext);
        }
        
        public MDM.BusinessObjects.OperationResult UpdateWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.UpdateWordList(wordList, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> UpdateWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.UpdateWordListAsync(wordList, callerContext);
        }
        
        public MDM.BusinessObjects.OperationResult DeleteWordList(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.DeleteWordList(wordList, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResult> DeleteWordListAsync(MDM.BusinessObjects.WordList wordList, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.DeleteWordListAsync(wordList, callerContext);
        }
        
        public MDM.BusinessObjects.OperationResultCollection ProcessWordLists(MDM.BusinessObjects.WordListsCollection wordLists, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.ProcessWordLists(wordLists, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.OperationResultCollection> ProcessWordListsAsync(MDM.BusinessObjects.WordListsCollection wordLists, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.ProcessWordListsAsync(wordLists, callerContext);
        }
        
        public MDM.BusinessObjects.WordElementsCollection GetWordElements(MDM.BusinessObjects.WordElementReportSettings pagingCriteria, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordElements(pagingCriteria, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.WordElementsCollection> GetWordElementsAsync(MDM.BusinessObjects.WordElementReportSettings pagingCriteria, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.GetWordElementsAsync(pagingCriteria, callerContext);
        }
        
        public MDM.BusinessObjects.WordElement CheckWordlistForDuplicateSubstitute(int wordlistId, string substitute, bool ignoreCase, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.CheckWordlistForDuplicateSubstitute(wordlistId, substitute, ignoreCase, callerContext);
        }
        
        public System.Threading.Tasks.Task<MDM.BusinessObjects.WordElement> CheckWordlistForDuplicateSubstituteAsync(int wordlistId, string substitute, bool ignoreCase, MDM.BusinessObjects.CallerContext callerContext) {
            return base.Channel.CheckWordlistForDuplicateSubstituteAsync(wordlistId, substitute, ignoreCase, callerContext);
        }
    }
}
